[phases.setup]
nixPkgs = ["nodejs_20", "python312", "python312Packages.numpy", "python312Packages.scipy"]

[phases.install]
cmds = ["npm install --legacy-peer-deps"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "node dist/index.cjs"
