[build]
builder = "nixpacks"
buildCommand = "npm ci && npm run build"

[deploy]
startCommand = "node dist/index.cjs"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[nixpacks]
aptPkgs = []

[nixpacks.environment]
NODE_VERSION = "20"
